# Gencraft Studio - Canonical yamllint Configuration
# SSoT: gcs-devops-standards/.yamllint.yaml
extends: default

rules:
  # It is impractical to enforce line length for configuration files.
  line-length:
    max: 120  # Increase limit to 120 characters.

  # Standardise l'indentation des commentaires.
  comments-indentation: enable

  # Autorise les commentaires en ligne avec un seul espace.
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
